"""empty message

Revision ID: dfc9207fae78
Revises: 
Create Date: 2020-08-29 23:58:06.367812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfc9207fae78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'src',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('files', 'title',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('gallery', 'preview_src',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('gallery', 'src',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.add_column('news', sa.Column('img', sa.Text(), nullable=True))
    op.alter_column('news', 'text',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('news', 'title',
               existing_type=mysql.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'title',
               existing_type=mysql.VARCHAR(length=140),
               nullable=True)
    op.alter_column('news', 'text',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('news', 'img')
    op.alter_column('gallery', 'src',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('gallery', 'preview_src',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('files', 'title',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('files', 'src',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
